# Generated by Django 4.1.3 on 2022-12-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("score", "0002_remove_player_life_time_score_remove_team_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
